// US cities with approximate population 25,000+, organized by state
// Source: US Census estimates, curated for billiards tournament coverage

export const US_CITIES_BY_STATE: Record<string, string[]> = {
  AL: [
    "Auburn", "Birmingham", "Decatur", "Dothan", "Florence", "Gadsden",
    "Hoover", "Huntsville", "Madison", "Mobile", "Montgomery", "Opelika",
    "Phenix City", "Prattville", "Tuscaloosa", "Vestavia Hills",
  ],
  AK: [
    "Anchorage", "Fairbanks", "Juneau",
  ],
  AZ: [
    "Avondale", "Buckeye", "Bullhead City", "Casa Grande", "Chandler",
    "Flagstaff", "Gilbert", "Glendale", "Goodyear", "Lake Havasu City",
    "Marana", "Maricopa", "Mesa", "Oro Valley", "Peoria", "Phoenix",
    "Prescott", "Prescott Valley", "Queen Creek", "San Tan Valley",
    "Scottsdale", "Sierra Vista", "Surprise", "Tempe", "Tucson", "Yuma",
  ],
  AR: [
    "Bentonville", "Conway", "Fayetteville", "Fort Smith", "Hot Springs",
    "Jonesboro", "Little Rock", "North Little Rock", "Pine Bluff",
    "Rogers", "Springdale", "Texarkana",
  ],
  CA: [
    "Alameda", "Alhambra", "Anaheim", "Antioch", "Apple Valley", "Arcadia",
    "Bakersfield", "Baldwin Park", "Beaumont", "Bell Gardens", "Berkeley",
    "Brea", "Brentwood", "Buena Park", "Burbank", "Camarillo", "Carlsbad",
    "Carson", "Cathedral City", "Ceres", "Cerritos", "Chico", "Chino",
    "Chino Hills", "Chula Vista", "Citrus Heights", "Clovis", "Colton",
    "Compton", "Concord", "Corona", "Costa Mesa", "Covina", "Cupertino",
    "Cypress", "Daly City", "Dana Point", "Davis", "Delano", "Diamond Bar",
    "Downey", "Dublin", "East Los Angeles", "Eastvale", "El Cajon",
    "El Centro", "El Monte", "Elk Grove", "Encinitas", "Escondido",
    "Fairfield", "Folsom", "Fontana", "Fountain Valley", "Fremont",
    "Fresno", "Fullerton", "Garden Grove", "Gardena", "Gilroy", "Glendale",
    "Glendora", "Hanford", "Hawthorne", "Hayward", "Hemet", "Hesperia",
    "Highland", "Huntington Beach", "Huntington Park", "Indio", "Inglewood",
    "Irvine", "Jurupa Valley", "La Habra", "La Mesa", "La Mirada",
    "La Quinta", "Laguna Niguel", "Lake Elsinore", "Lake Forest",
    "Lakewood", "Lancaster", "Livermore", "Lodi", "Lompoc", "Long Beach",
    "Los Angeles", "Lynwood", "Madera", "Manteca", "Menifee", "Merced",
    "Milpitas", "Mission Viejo", "Modesto", "Monrovia", "Montclair",
    "Montebello", "Monterey Park", "Moreno Valley", "Morgan Hill",
    "Mountain View", "Murrieta", "Napa", "National City", "Newark",
    "Newport Beach", "Norco", "Norwalk", "Novato", "Oakland", "Oceanside",
    "Ontario", "Orange", "Oxnard", "Palm Desert", "Palm Springs",
    "Palmdale", "Palo Alto", "Paramount", "Pasadena", "Perris", "Petaluma",
    "Pico Rivera", "Pittsburg", "Placentia", "Pleasanton", "Pomona",
    "Porterville", "Rancho Cordova", "Rancho Cucamonga",
    "Rancho Palos Verdes", "Rancho Santa Margarita", "Redding",
    "Redlands", "Redondo Beach", "Redwood City", "Rialto", "Richmond",
    "Riverside", "Rocklin", "Rosemead", "Roseville", "Sacramento",
    "Salinas", "San Bernardino", "San Bruno", "San Buenaventura",
    "San Clemente", "San Diego", "San Dimas", "San Francisco",
    "San Jacinto", "San Jose", "San Juan Capistrano", "San Leandro",
    "San Luis Obispo", "San Marcos", "San Mateo", "San Rafael",
    "San Ramon", "Santa Ana", "Santa Barbara", "Santa Clara",
    "Santa Clarita", "Santa Cruz", "Santa Maria", "Santa Monica",
    "Santa Rosa", "Santee", "Simi Valley", "South Gate", "South San Francisco",
    "Stockton", "Sunnyvale", "Temecula", "Thousand Oaks", "Torrance",
    "Tracy", "Tulare", "Turlock", "Tustin", "Union City", "Upland",
    "Vacaville", "Vallejo", "Victorville", "Visalia", "Vista", "Walnut",
    "Walnut Creek", "Watsonville", "West Covina", "West Sacramento",
    "Westminster", "Whittier", "Woodland", "Yorba Linda", "Yuba City",
    "Yucaipa",
  ],
  CO: [
    "Arvada", "Aurora", "Boulder", "Broomfield", "Castle Rock",
    "Centennial", "Colorado Springs", "Commerce City", "Denver",
    "Englewood", "Erie", "Fort Collins", "Grand Junction", "Greeley",
    "Highlands Ranch", "Lakewood", "Littleton", "Longmont", "Loveland",
    "Northglenn", "Parker", "Pueblo", "Thornton", "Westminster",
    "Wheat Ridge", "Windsor",
  ],
  CT: [
    "Bridgeport", "Bristol", "Danbury", "East Hartford", "Fairfield",
    "Greenwich", "Hamden", "Hartford", "Manchester", "Meriden",
    "Middletown", "Milford", "Naugatuck", "New Britain", "New Haven",
    "Newington", "Norwalk", "Norwich", "Shelton", "Stamford",
    "Stratford", "Torrington", "Wallingford", "Waterbury", "West Hartford",
    "West Haven", "Westport",
  ],
  DE: [
    "Dover", "Newark", "Wilmington",
  ],
  FL: [
    "Altamonte Springs", "Apopka", "Aventura", "Boca Raton", "Bonita Springs",
    "Boynton Beach", "Bradenton", "Brandon", "Cape Coral", "Clearwater",
    "Clermont", "Coconut Creek", "Cooper City", "Coral Gables",
    "Coral Springs", "Cutler Bay", "Davie", "Daytona Beach", "Deerfield Beach",
    "Delray Beach", "Deltona", "Doral", "Dunedin", "Fort Lauderdale",
    "Fort Myers", "Fort Pierce", "Gainesville", "Greenacres", "Hallandale Beach",
    "Hialeah", "Hollywood", "Homestead", "Jacksonville", "Jupiter",
    "Kendale Lakes", "Kendall", "Kissimmee", "Lake Worth", "Lakeland",
    "Largo", "Lauderhill", "Lehigh Acres", "Margate", "Melbourne",
    "Miami", "Miami Beach", "Miami Gardens", "Miramar", "Naples",
    "North Lauderdale", "North Miami", "North Miami Beach", "North Port",
    "Oakland Park", "Ocala", "Orlando", "Ormond Beach", "Oviedo",
    "Palm Bay", "Palm Beach Gardens", "Palm Coast", "Panama City",
    "Pembroke Pines", "Pensacola", "Pine Hills", "Pinellas Park",
    "Plant City", "Plantation", "Poinciana", "Pompano Beach",
    "Port Charlotte", "Port Orange", "Port St. Lucie", "Riverview",
    "Royal Palm Beach", "Sanford", "Sarasota", "Spring Hill",
    "St. Cloud", "St. Petersburg", "Sunrise", "Tallahassee", "Tamarac",
    "Tampa", "Titusville", "Wellington", "Wesley Chapel",
    "West Palm Beach", "Weston", "Winter Garden", "Winter Haven",
    "Winter Park", "Winter Springs",
  ],
  GA: [
    "Albany", "Alpharetta", "Athens", "Atlanta", "Augusta", "Brookhaven",
    "Canton", "Columbus", "Dalton", "Douglasville", "Dunwoody",
    "East Point", "Gainesville", "Hinesville", "Johns Creek",
    "Kennesaw", "Lawrenceville", "Macon", "Marietta", "Milton",
    "Newnan", "Peachtree City", "Peachtree Corners", "Pooler",
    "Roswell", "Sandy Springs", "Savannah", "Smyrna", "Statesboro",
    "Stonecrest", "Tucker", "Valdosta", "Warner Robins", "Woodstock",
  ],
  HI: [
    "East Honolulu", "Hilo", "Honolulu", "Kahului", "Kailua",
    "Kaneohe", "Pearl City", "Waipahu",
  ],
  ID: [
    "Boise", "Caldwell", "Coeur d'Alene", "Idaho Falls", "Lewiston",
    "Meridian", "Nampa", "Pocatello", "Twin Falls",
  ],
  IL: [
    "Addison", "Algonquin", "Arlington Heights", "Aurora", "Bartlett",
    "Belleville", "Berwyn", "Bloomington", "Bolingbrook", "Buffalo Grove",
    "Calumet City", "Carol Stream", "Carpentersville", "Champaign",
    "Chicago", "Cicero", "Crystal Lake", "Danville", "DeKalb",
    "Decatur", "Des Plaines", "Downers Grove", "East St. Louis",
    "Elgin", "Elk Grove Village", "Elmhurst", "Evanston", "Glendale Heights",
    "Glenview", "Granite City", "Gurnee", "Hanover Park", "Hoffman Estates",
    "Homer Glen", "Huntley", "Joliet", "Kankakee", "Lake in the Hills",
    "Lansing", "Lombard", "McHenry", "Moline", "Mount Prospect",
    "Mundelein", "Naperville", "Normal", "North Chicago", "Northbrook",
    "O'Fallon", "Oak Forest", "Oak Lawn", "Oak Park", "Orland Park",
    "Oswego", "Palatine", "Park Ridge", "Pekin", "Peoria",
    "Plainfield", "Quincy", "Rock Island", "Rockford", "Romeoville",
    "Round Lake Beach", "Schaumburg", "Skokie", "Springfield",
    "St. Charles", "Streamwood", "Tinley Park", "Urbana", "Vernon Hills",
    "Waukegan", "West Chicago", "Wheaton", "Wheeling", "Woodridge",
  ],
  IN: [
    "Anderson", "Bloomington", "Carmel", "Columbus", "Elkhart",
    "Evansville", "Fishers", "Fort Wayne", "Gary", "Goshen",
    "Greenfield", "Greenwood", "Hammond", "Indianapolis", "Jeffersonville",
    "Kokomo", "Lafayette", "Lawrence", "Merrillville", "Michigan City",
    "Mishawaka", "Muncie", "New Albany", "Noblesville", "Plainfield",
    "Portage", "Richmond", "South Bend", "Terre Haute", "Westfield",
    "Zionsville",
  ],
  IA: [
    "Ames", "Ankeny", "Cedar Falls", "Cedar Rapids", "Council Bluffs",
    "Davenport", "Des Moines", "Dubuque", "Iowa City", "Marion",
    "Sioux City", "Urbandale", "Waterloo", "West Des Moines",
  ],
  KS: [
    "Derby", "Dodge City", "Garden City", "Hutchinson", "Kansas City",
    "Lawrence", "Leavenworth", "Lenexa", "Manhattan", "Olathe",
    "Overland Park", "Salina", "Shawnee", "Topeka", "Wichita",
  ],
  KY: [
    "Bowling Green", "Covington", "Elizabethtown", "Florence",
    "Frankfort", "Georgetown", "Henderson", "Hopkinsville",
    "Lexington", "Louisville", "Nicholasville", "Owensboro",
    "Paducah", "Richmond",
  ],
  LA: [
    "Alexandria", "Baton Rouge", "Bossier City", "Central", "Harvey",
    "Houma", "Kenner", "Lafayette", "Lake Charles", "Laplace",
    "Marrero", "Metairie", "Monroe", "New Iberia", "New Orleans",
    "Ruston", "Shreveport", "Slidell", "Sulphur", "Terrytown",
  ],
  ME: [
    "Bangor", "Lewiston", "Portland", "South Portland",
  ],
  MD: [
    "Annapolis", "Baltimore", "Bel Air", "Bethesda", "Bowie",
    "Catonsville", "College Park", "Columbia", "Dundalk", "Ellicott City",
    "Frederick", "Gaithersburg", "Germantown", "Glen Burnie", "Hagerstown",
    "Laurel", "Odenton", "Olney", "Owings Mills", "Rockville",
    "Salisbury", "Severn", "Severna Park", "Silver Spring", "Towson",
    "Waldorf", "Wheaton",
  ],
  MA: [
    "Barnstable", "Beverly", "Boston", "Brockton", "Brookline",
    "Cambridge", "Chicopee", "Everett", "Fall River", "Framingham",
    "Haverhill", "Holyoke", "Lawrence", "Leominster", "Lowell",
    "Lynn", "Malden", "Marlborough", "Medford", "Methuen", "New Bedford",
    "Newton", "Peabody", "Pittsfield", "Plymouth", "Quincy", "Revere",
    "Salem", "Somerville", "Springfield", "Taunton", "Waltham",
    "Weymouth", "Woburn", "Worcester",
  ],
  MI: [
    "Ann Arbor", "Battle Creek", "Bay City", "Dearborn", "Dearborn Heights",
    "Detroit", "East Lansing", "Farmington Hills", "Flint", "Grand Rapids",
    "Holland", "Jackson", "Kalamazoo", "Kentwood", "Lansing",
    "Lincoln Park", "Livonia", "Macomb", "Midland", "Muskegon",
    "Novi", "Pontiac", "Portage", "Rochester Hills", "Roseville",
    "Royal Oak", "Saginaw", "Shelby Township", "Southfield",
    "Southgate", "Sterling Heights", "Taylor", "Troy", "Warren",
    "Westland", "Wyoming",
  ],
  MN: [
    "Apple Valley", "Blaine", "Bloomington", "Brooklyn Park",
    "Burnsville", "Coon Rapids", "Cottage Grove", "Duluth",
    "Eagan", "Eden Prairie", "Edina", "Lakeville", "Mankato",
    "Maple Grove", "Maplewood", "Minneapolis", "Minnetonka",
    "Moorhead", "Plymouth", "Prior Lake", "Richfield", "Rochester",
    "Rosemount", "Roseville", "Savage", "Shakopee", "St. Cloud",
    "St. Louis Park", "St. Paul", "Woodbury",
  ],
  MS: [
    "Biloxi", "Brandon", "Clinton", "Columbus", "Greenville",
    "Gulfport", "Hattiesburg", "Horn Lake", "Jackson", "Madison",
    "Meridian", "Olive Branch", "Oxford", "Pearl", "Ridgeland",
    "Southaven", "Starkville", "Tupelo", "Vicksburg",
  ],
  MO: [
    "Ballwin", "Blue Springs", "Cape Girardeau", "Chesterfield",
    "Columbia", "Florissant", "Gladstone", "Hazelwood", "Independence",
    "Jefferson City", "Joplin", "Kansas City", "Kirkwood", "Lee's Summit",
    "Liberty", "Maryland Heights", "O'Fallon", "Raymore", "Raytown",
    "Springfield", "St. Charles", "St. Joseph", "St. Louis", "St. Peters",
    "University City", "Wentzville", "Wildwood",
  ],
  MT: [
    "Billings", "Bozeman", "Great Falls", "Helena", "Missoula",
  ],
  NE: [
    "Bellevue", "Columbus", "Fremont", "Grand Island", "Kearney",
    "Lincoln", "Norfolk", "Omaha", "Papillion",
  ],
  NV: [
    "Carson City", "Enterprise", "Henderson", "Las Vegas", "North Las Vegas",
    "Paradise", "Reno", "Sparks", "Spring Valley", "Sunrise Manor",
    "Whitney", "Winchester",
  ],
  NH: [
    "Concord", "Derry", "Dover", "Manchester", "Nashua", "Rochester",
  ],
  NJ: [
    "Atlantic City", "Bayonne", "Bergenfield", "Bloomfield", "Bridgewater",
    "Camden", "Cherry Hill", "Clifton", "East Brunswick", "East Orange",
    "Edison", "Elizabeth", "Englewood", "Ewing", "Fair Lawn",
    "Fort Lee", "Franklin", "Garfield", "Hackensack", "Hamilton",
    "Hoboken", "Irvington", "Jackson", "Jersey City", "Kearny",
    "Lakewood", "Linden", "Livingston", "Long Branch", "Manalapan",
    "Marlboro", "Middletown", "Monroe", "Montclair", "New Brunswick",
    "Newark", "North Bergen", "North Brunswick", "Old Bridge",
    "Parsippany", "Passaic", "Paterson", "Piscataway", "Plainfield",
    "Princeton", "Rahway", "Sayreville", "Teaneck", "Toms River",
    "Trenton", "Union", "Union City", "Vineland", "Wayne",
    "West New York", "West Orange", "Westfield", "Woodbridge",
  ],
  NM: [
    "Albuquerque", "Clovis", "Farmington", "Hobbs", "Las Cruces",
    "Rio Rancho", "Roswell", "Santa Fe", "South Valley",
  ],
  NY: [
    "Albany", "Amherst", "Babylon", "Binghamton", "Brighton",
    "Brookhaven", "Brooklyn", "Buffalo", "Cheektowaga", "Clarkstown",
    "Colonie", "Freeport", "Greece", "Greenburgh", "Hamburg",
    "Hempstead", "Huntington", "Irondequoit", "Islip", "Ithaca",
    "Levittown", "Long Beach", "Manhattan", "Mount Vernon",
    "New Rochelle", "New York City", "Newburgh", "Niagara Falls",
    "North Hempstead", "Oyster Bay", "Perinton", "Poughkeepsie",
    "Queens", "Ramapo", "Rochester", "Schenectady", "Smithtown",
    "Spring Valley", "Staten Island", "Syracuse", "The Bronx",
    "Troy", "Utica", "Valley Stream", "West Seneca", "White Plains",
    "Yonkers",
  ],
  NC: [
    "Apex", "Asheville", "Burlington", "Cary", "Chapel Hill",
    "Charlotte", "Concord", "Durham", "Fayetteville", "Fuquay-Varina",
    "Garner", "Gastonia", "Goldsboro", "Greensboro", "Greenville",
    "Hickory", "High Point", "Holly Springs", "Huntersville",
    "Indian Trail", "Jacksonville", "Kannapolis", "Leland", "Mooresville",
    "Morrisville", "New Bern", "Raleigh", "Rocky Mount", "Sanford",
    "Thomasville", "Wake Forest", "Wilmington", "Wilson", "Winston-Salem",
  ],
  ND: [
    "Bismarck", "Fargo", "Grand Forks", "Minot", "West Fargo",
  ],
  OH: [
    "Akron", "Barberton", "Beavercreek", "Boardman", "Brunswick",
    "Canton", "Cincinnati", "Cleveland", "Cleveland Heights", "Columbus",
    "Cuyahoga Falls", "Dayton", "Delaware", "Dublin", "Elyria",
    "Euclid", "Fairborn", "Fairfield", "Findlay", "Grove City",
    "Hamilton", "Hilliard", "Huber Heights", "Kent", "Kettering",
    "Lakewood", "Lancaster", "Lima", "Lorain", "Mansfield",
    "Mason", "Medina", "Mentor", "Middletown", "Newark",
    "North Olmsted", "North Ridgeville", "North Royalton",
    "Parma", "Reynoldsburg", "Sandusky", "Springfield", "Stow",
    "Strongsville", "Toledo", "Upper Arlington", "Warren",
    "Westerville", "Westlake", "Wooster", "Youngstown", "Zanesville",
  ],
  OK: [
    "Bartlesville", "Bethany", "Bixby", "Broken Arrow", "Del City",
    "Edmond", "Enid", "Lawton", "Midwest City", "Moore",
    "Muskogee", "Norman", "Oklahoma City", "Owasso", "Ponca City",
    "Shawnee", "Stillwater", "Tulsa", "Yukon",
  ],
  OR: [
    "Albany", "Aloha", "Beaverton", "Bend", "Corvallis", "Eugene",
    "Grants Pass", "Gresham", "Hillsboro", "Keizer", "Lake Oswego",
    "McMinnville", "Medford", "Oregon City", "Portland", "Redmond",
    "Salem", "Springfield", "Tigard", "Tualatin", "West Linn",
    "Woodburn",
  ],
  PA: [
    "Abington", "Allentown", "Altoona", "Bethel Park", "Bethlehem",
    "Bucks County", "Chester", "Cranberry Township", "Drexel Hill",
    "Easton", "Erie", "Harrisburg", "Haverford", "Hazleton",
    "King of Prussia", "Lancaster", "Lansdale", "Lebanon",
    "Levittown", "Lower Merion", "Monroeville", "Norristown",
    "Philadelphia", "Pittsburgh", "Pottstown", "Reading", "Scranton",
    "State College", "Upper Darby", "West Chester", "West Mifflin",
    "Wilkes-Barre", "Williamsport", "York",
  ],
  RI: [
    "Cranston", "East Providence", "Pawtucket", "Providence",
    "Warwick", "Woonsocket",
  ],
  SC: [
    "Aiken", "Anderson", "Charleston", "Columbia", "Florence",
    "Fort Mill", "Goose Creek", "Greenville", "Greer", "Hilton Head Island",
    "Mauldin", "Mount Pleasant", "Myrtle Beach", "North Augusta",
    "North Charleston", "Rock Hill", "Simpsonville", "Spartanburg",
    "Summerville", "Sumter", "Taylors",
  ],
  SD: [
    "Aberdeen", "Brookings", "Rapid City", "Sioux Falls", "Watertown",
  ],
  TN: [
    "Bartlett", "Brentwood", "Chattanooga", "Clarksville", "Cleveland",
    "Collierville", "Columbia", "Cookeville", "Franklin", "Gallatin",
    "Germantown", "Hendersonville", "Jackson", "Johnson City",
    "Kingsport", "Knoxville", "La Vergne", "Lebanon", "Maryville",
    "Memphis", "Morristown", "Mount Juliet", "Murfreesboro", "Nashville",
    "Oak Ridge", "Smyrna", "Spring Hill",
  ],
  TX: [
    "Abilene", "Allen", "Amarillo", "Arlington", "Austin",
    "Baytown", "Beaumont", "Bedford", "Brownsville", "Bryan",
    "Burleson", "Carrollton", "Cedar Hill", "Cedar Park", "Channelview",
    "College Station", "Conroe", "Coppell", "Corpus Christi", "Dallas",
    "Denton", "DeSoto", "Duncanville", "Edinburg", "El Paso",
    "Euless", "Flower Mound", "Fort Worth", "Frisco", "Galveston",
    "Garland", "Georgetown", "Grand Prairie", "Grapevine", "Haltom City",
    "Harlingen", "Houston", "Humble", "Hurst", "Irving",
    "Katy", "Keller", "Killeen", "Kyle", "Laredo",
    "League City", "Leander", "Lewisville", "Little Elm", "Longview",
    "Lubbock", "Lufkin", "Mansfield", "McAllen", "McKinney",
    "Mesquite", "Midland", "Mission", "Missouri City", "Murphy",
    "New Braunfels", "North Richland Hills", "Odessa", "Pasadena",
    "Pearland", "Pflugerville", "Pharr", "Plano", "Port Arthur",
    "Princeton", "Prosper", "Richardson", "Rockwall", "Round Rock",
    "Rowlett", "Sachse", "San Angelo", "San Antonio", "San Marcos",
    "Schertz", "Sherman", "Socorro", "Spring", "Sugar Land",
    "Temple", "Texarkana", "Texas City", "The Colony", "The Woodlands",
    "Tyler", "Victoria", "Waco", "Watauga", "Waxahachie",
    "Weatherford", "Weslaco", "Wichita Falls", "Wylie",
  ],
  UT: [
    "American Fork", "Bountiful", "Cedar City", "Clearfield", "Cottonwood Heights",
    "Draper", "Eagle Mountain", "Herriman", "Holladay", "Kaysville",
    "Layton", "Lehi", "Logan", "Midvale", "Murray",
    "Ogden", "Orem", "Pleasant Grove", "Provo", "Riverton",
    "Roy", "Salt Lake City", "Sandy", "Saratoga Springs",
    "South Jordan", "South Salt Lake", "Spanish Fork", "Springville",
    "St. George", "Taylorsville", "Tooele", "West Jordan",
    "West Valley City",
  ],
  VT: [
    "Burlington", "South Burlington",
  ],
  VA: [
    "Alexandria", "Annandale", "Arlington", "Ashburn", "Burke",
    "Centreville", "Charlottesville", "Chesapeake", "Dale City",
    "Danville", "Fairfax", "Fredericksburg", "Hampton", "Harrisonburg",
    "Herndon", "Lake Ridge", "Leesburg", "Lynchburg", "Manassas",
    "McLean", "Mechanicsville", "Newport News", "Norfolk",
    "Petersburg", "Portsmouth", "Reston", "Richmond", "Roanoke",
    "Springfield", "Sterling", "Suffolk", "Tuckahoe",
    "Virginia Beach", "Woodbridge",
  ],
  WA: [
    "Auburn", "Bellevue", "Bellingham", "Bothell", "Bremerton",
    "Burien", "Centralia", "Des Moines", "Edmonds", "Everett",
    "Federal Way", "Kennewick", "Kent", "Kirkland", "Lacey",
    "Lake Stevens", "Lakewood", "Lynnwood", "Marysville", "Mercer Island",
    "Moses Lake", "Mount Vernon", "Olympia", "Pasco", "Pullman",
    "Puyallup", "Redmond", "Renton", "Richland", "Sammamish",
    "SeaTac", "Seattle", "Shoreline", "Spokane", "Spokane Valley",
    "Tacoma", "Tukwila", "University Place", "Vancouver", "Walla Walla",
    "Wenatchee", "Yakima",
  ],
  WV: [
    "Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling",
  ],
  WI: [
    "Appleton", "Beloit", "Brookfield", "Caledonia", "Eau Claire",
    "Fitchburg", "Fond du Lac", "Franklin", "Green Bay", "Greenfield",
    "Janesville", "Kenosha", "La Crosse", "Madison", "Manitowoc",
    "Menomonee Falls", "Milwaukee", "Mount Pleasant", "Muskego",
    "New Berlin", "Oak Creek", "Oshkosh", "Racine", "Sheboygan",
    "Stevens Point", "Sun Prairie", "Waukesha", "Wausau",
    "Wauwatosa", "West Allis",
  ],
  WY: [
    "Casper", "Cheyenne", "Gillette", "Laramie", "Rock Springs",
  ],
};
