import { ROLES } from './roles';

export const PERMISSIONS = {
  BROWSE_TOURNAMENTS: [ROLES.BASIC_USER, ROLES.TOURNAMENT_DIRECTOR, ROLES.BAR_OWNER, ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  SUBMIT_TOURNAMENT: [ROLES.TOURNAMENT_DIRECTOR, ROLES.BAR_OWNER, ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  EDIT_OWN_TOURNAMENT: [ROLES.TOURNAMENT_DIRECTOR, ROLES.BAR_OWNER, ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  EDIT_ANY_TOURNAMENT: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  DELETE_TOURNAMENT: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  
  CREATE_VENUE: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  EDIT_OWN_VENUE: [ROLES.BAR_OWNER, ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  EDIT_ANY_VENUE: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  DELETE_VENUE: [ROLES.BAR_OWNER, ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  ASSIGN_DIRECTORS: [ROLES.BAR_OWNER, ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  
  CREATE_GIVEAWAY: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  DRAW_WINNER: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  
  VIEW_USERS: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  EDIT_USER_ROLE: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  BAN_USER: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  
  MANAGE_ADMINS: [ROLES.SUPER_ADMIN],
  VIEW_AUDIT_LOG: [ROLES.SUPER_ADMIN],
  RESTORE_ARCHIVED: [ROLES.SUPER_ADMIN],
  
  MANAGE_FAQS: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  VIEW_SUPPORT_TICKETS: [ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  
  SEND_TOURNAMENT_MESSAGE: [ROLES.TOURNAMENT_DIRECTOR, ROLES.BAR_OWNER, ROLES.COMPETE_ADMIN, ROLES.SUPER_ADMIN],
  SEND_BROADCAST_MESSAGE: [ROLES.SUPER_ADMIN],
} as const;

export type Permission = keyof typeof PERMISSIONS;